import { TopicCategory } from "@/types/quiz";

export const TOPIC_CATEGORIES: TopicCategory[] = [
  // Computer Science Basics
  {
    id: "dsa",
    title: "Data Structures & Algorithms",
    description: "Arrays, Trees, Graphs, Sorting, Hash Maps, Big-O Complexity & Dynamic Programming",
    category: "cs_basics",
    iconName: "GitBranch",
    defaultDifficulty: "intermediate",
    subtopics: ["Arrays & HashMaps", "Trees & BST", "Graphs & BFS/DFS", "Sorting & Searching", "Dynamic Programming"],
  },
  {
    id: "networks",
    title: "Computer Networks",
    description: "OSI Model, TCP/UDP, HTTP/HTTPS, WebSockets, DNS, CORS & TLS handshake",
    category: "cs_basics",
    iconName: "Network",
    defaultDifficulty: "intermediate",
    subtopics: ["OSI & TCP/IP Layers", "HTTP Protocols & REST", "TCP vs UDP Handshakes", "DNS & Routing", "WebSockets & SSE"],
  },
  {
    id: "oop",
    title: "OOP & System Design Patterns",
    description: "Inheritance, Polymorphism, Encapsulation, SOLID principles, Factory & Singleton",
    category: "cs_basics",
    iconName: "Layers",
    defaultDifficulty: "intermediate",
    subtopics: ["Encapsulation & Polymorphism", "SOLID Principles", "Creational Patterns", "Structural Patterns", "Behavioral Patterns"],
  },
  {
    id: "databases",
    title: "Databases & SQL Theory",
    description: "ACID, Indexing, B-Trees, Normalization, Query Optimization & NoSQL vs SQL",
    category: "cs_basics",
    iconName: "Database",
    defaultDifficulty: "intermediate",
    subtopics: ["ACID & Transactions", "B-Tree & Indexing", "Normalization (1NF-BCNF)", "Query Execution & Locks", "SQL vs NoSQL CAP"],
  },
  {
    id: "os",
    title: "Operating Systems",
    description: "Processes vs Threads, Concurrency, Deadlocks, Virtual Memory & Syscalls",
    category: "cs_basics",
    iconName: "Cpu",
    defaultDifficulty: "advanced",
    subtopics: ["Process & Thread Scheduling", "Deadlocks & Mutexes", "Virtual Memory & Paging", "Context Switching", "File Systems"],
  },
  {
    id: "data-engineering",
    title: "Data Engineering",
    description: "Batch vs Stream processing, ETL pipelines, Distributed computing, Kafka & Spark",
    category: "cs_basics",
    iconName: "Binary",
    defaultDifficulty: "intermediate",
    subtopics: ["ETL vs ELT Pipelines", "Stream Processing (Kafka)", "Distributed Computing (Spark)", "Data Warehousing & Lakehouse", "Data Partitioning"],
  },
  {
    id: "ml-basics",
    title: "Machine Learning Fundamentals",
    description: "Supervised vs Unsupervised, Bias-Variance, Evaluation metrics, Loss functions",
    category: "cs_basics",
    iconName: "Sparkles",
    defaultDifficulty: "beginner",
    subtopics: ["Supervised vs Unsupervised", "Overfitting & Regularization", "Precision, Recall & ROC-AUC", "Gradient Descent", "Loss Functions"],
  },

  // Code Snippets & Output Prediction
  {
    id: "js-output",
    title: "JavaScript / TypeScript Snippets",
    description: "Event Loop, Closures, `this` Binding, Async/Await, Microtasks & Type Coercion",
    category: "code_snippets",
    iconName: "Code2",
    defaultDifficulty: "intermediate",
    subtopics: ["Event Loop & Microtasks", "Closures & Scope", "this & Prototype Chain", "Promises & Async/Await", "Type Coercion"],
  },
  {
    id: "python-output",
    title: "Python Snippets & Quirks",
    description: "Mutability defaults, Scoping (LEGB), Generators, Decorators, Unpacking & GIL",
    category: "code_snippets",
    iconName: "Terminal",
    defaultDifficulty: "intermediate",
    subtopics: ["Default Mutable Arguments", "LEGB Scope & Closures", "Generators & Yield", "Decorators & Wrappers", "List/Dict Comprehensions"],
  },
  {
    id: "react-output",
    title: "React Lifecycle & State Logic",
    description: "Hook lifecycles, Stale closures, Batch re-rendering, State mutation vs immutability",
    category: "code_snippets",
    iconName: "Workflow",
    defaultDifficulty: "intermediate",
    subtopics: ["useEffect Dependency Quirks", "Stale Closures in Hooks", "Batching State Updates", "Memoization & Re-renders", "Ref vs State"],
  },
  {
    id: "sql-output",
    title: "SQL Query Output & Logic",
    description: "Complex Joins, NULL arithmetic, GROUP BY execution order & Window functions",
    category: "code_snippets",
    iconName: "FileCode",
    defaultDifficulty: "intermediate",
    subtopics: ["LEFT vs INNER Joins with NULL", "GROUP BY & HAVING order", "Window Functions (ROW_NUMBER)", "Subqueries & EXISTS", "CASE WHEN Logic"],
  },
];
