-- Seed Topics
INSERT OR IGNORE INTO topics (id, title, description, category, iconName, defaultDifficulty, subtopicsJson, createdAt)
VALUES
  ('dsa', 'Data Structures & Algorithms', 'Arrays, Trees, Graphs, Sorting, Hash Maps, Big-O Complexity & Dynamic Programming', 'cs_basics', 'GitBranch', 'intermediate', '["Arrays & HashMaps", "Trees & BST", "Graphs & BFS/DFS", "Sorting & Searching", "Dynamic Programming"]', datetime('now')),
  ('networks', 'Computer Networks', 'OSI Model, TCP/UDP, HTTP/HTTPS, WebSockets, DNS, CORS & TLS handshake', 'cs_basics', 'Network', 'intermediate', '["OSI & TCP/IP Layers", "HTTP Protocols & REST", "TCP vs UDP Handshakes", "DNS & Routing", "WebSockets & SSE"]', datetime('now')),
  ('oop', 'OOP & System Design Patterns', 'Inheritance, Polymorphism, Encapsulation, SOLID principles, Factory & Singleton', 'cs_basics', 'Layers', 'intermediate', '["Encapsulation & Polymorphism", "SOLID Principles", "Creational Patterns", "Structural Patterns", "Behavioral Patterns"]', datetime('now')),
  ('databases', 'Databases & SQL Theory', 'ACID, Indexing, B-Trees, Normalization, Query Optimization & NoSQL vs SQL', 'cs_basics', 'Database', 'intermediate', '["ACID & Transactions", "B-Tree & Indexing", "Normalization (1NF-BCNF)", "Query Execution & Locks", "SQL vs NoSQL CAP"]', datetime('now')),
  ('os', 'Operating Systems', 'Processes vs Threads, Concurrency, Deadlocks, Virtual Memory & Syscalls', 'cs_basics', 'Cpu', 'advanced', '["Process & Thread Scheduling", "Deadlocks & Mutexes", "Virtual Memory & Paging", "Context Switching", "File Systems"]', datetime('now')),
  ('data-engineering', 'Data Engineering', 'Batch vs Stream processing, ETL pipelines, Distributed computing, Kafka & Spark', 'cs_basics', 'Binary', 'intermediate', '["ETL vs ELT Pipelines", "Stream Processing (Kafka)", "Distributed Computing (Spark)", "Data Warehousing & Lakehouse", "Data Partitioning"]', datetime('now')),
  ('ml-basics', 'Machine Learning Fundamentals', 'Supervised vs Unsupervised, Bias-Variance, Evaluation metrics, Loss functions', 'cs_basics', 'Sparkles', 'beginner', '["Supervised vs Unsupervised", "Overfitting & Regularization", "Precision, Recall & ROC-AUC", "Gradient Descent", "Loss Functions"]', datetime('now')),
  ('js-output', 'JavaScript / TypeScript Snippets', 'Event Loop, Closures, this Binding, Async/Await, Microtasks & Type Coercion', 'code_snippets', 'Code2', 'intermediate', '["Event Loop & Microtasks", "Closures & Scope", "this & Prototype Chain", "Promises & Async/Await", "Type Coercion"]', datetime('now')),
  ('python-output', 'Python Snippets & Quirks', 'Mutability defaults, Scoping (LEGB), Generators, Decorators, Unpacking & GIL', 'code_snippets', 'Terminal', 'intermediate', '["Default Mutable Arguments", "LEGB Scope & Closures", "Generators & Yield", "Decorators & Wrappers", "List/Dict Comprehensions"]', datetime('now')),
  ('react-output', 'React Lifecycle & State Logic', 'Hook lifecycles, Stale closures, Batch re-rendering, State mutation vs immutability', 'code_snippets', 'Workflow', 'intermediate', '["useEffect Dependency Quirks", "Stale Closures in Hooks", "Batching State Updates", "Memoization & Re-renders", "Ref vs State"]', datetime('now')),
  ('sql-output', 'SQL Query Output & Logic', 'Complex Joins, NULL arithmetic, GROUP BY execution order & Window functions', 'code_snippets', 'FileCode', 'intermediate', '["LEFT vs INNER Joins with NULL", "GROUP BY & HAVING order", "Window Functions (ROW_NUMBER)", "Subqueries & EXISTS", "CASE WHEN Logic"]', datetime('now'));

-- Seed Questions
INSERT OR IGNORE INTO questions (id, topicId, topicTitle, subtopic, type, difficulty, question, codeSnippet, language, optionsJson, correctAnswerIndex, explanation, keyTakeaway, createdAt)
VALUES
  ('seed-js-1', 'js-output', 'JavaScript / TypeScript Snippets', 'Event Loop', 'code_output', 'intermediate',
   'What will be printed to the console when the following code runs?',
   'console.log(''1'');\n\nsetTimeout(() => {\n  console.log(''2'');\n}, 0);\n\nPromise.resolve().then(() => {\n  console.log(''3'');\n});\n\nconsole.log(''4'');',
   'javascript',
   '["1, 2, 3, 4", "1, 4, 2, 3", "1, 4, 3, 2", "1, 3, 4, 2"]',
   2,
   'Synchronous code runs first (1, 4). Microtasks from Promise.resolve() execute before the next macrotask (3). Finally, the setTimeout macrotask runs (2).',
   'Microtasks (Promises) execute before Macrotasks (setTimeout, setInterval).',
   datetime('now')),

  ('seed-js-2', 'js-output', 'JavaScript / TypeScript Snippets', 'Array Methods', 'code_output', 'intermediate',
   'What is the output of the following function invocation?',
   'const numbers = [1, 2, 3, 4];\n\nconst result = numbers.map(num => {\n  if (num > 2) return num * 2;\n});\n\nconsole.log(result);',
   'javascript',
   '["[6, 8]", "[undefined, undefined, 6, 8]", "[null, null, 6, 8]", "[0, 0, 6, 8]"]',
   1,
   'Array.prototype.map returns an array of the same length as the original. Branch without an explicit return defaults to undefined.',
   'Use .filter() before .map() or .flatMap() to omit elements without leaving undefined slots.',
   datetime('now')),

  ('seed-dsa-1', 'dsa', 'Data Structures & Algorithms', 'Trees', 'mcq', 'intermediate',
   'What is the worst-case time complexity of searching in an unbalanced Binary Search Tree (BST)?',
   NULL,
   NULL,
   '["O(1)", "O(log n)", "O(n)", "O(n log n)"]',
   2,
   'When elements are inserted in sorted order, an unbalanced BST degenerates into a singly linked list with depth n, requiring O(n) worst-case search.',
   'Self-balancing trees (AVL, Red-Black) guarantee O(log n) search by performing tree rotations.',
   datetime('now')),

  ('seed-dsa-2', 'dsa', 'Data Structures & Algorithms', 'Graphs', 'mcq', 'intermediate',
   'Which data structure is typically used to implement Breadth-First Search (BFS) in a graph?',
   NULL,
   NULL,
   '["Stack", "Queue", "Priority Queue", "Min-Heap"]',
   1,
   'BFS explores nodes level by level using a FIFO (First-In, First-Out) Queue. In contrast, DFS uses a LIFO Stack or recursive call stack.',
   'Queues enforce level-order FIFO traversal in graph and tree breadth-first searches.',
   datetime('now')),

  ('seed-networks-1', 'networks', 'Computer Networks', 'OSI Layers', 'mcq', 'intermediate',
   'Which layer of the OSI model is responsible for end-to-end communication, flow control, and error recovery (e.g. TCP)?',
   NULL,
   NULL,
   '["Network Layer (Layer 3)", "Transport Layer (Layer 4)", "Data Link Layer (Layer 2)", "Session Layer (Layer 5)"]',
   1,
   'The Transport Layer (Layer 4) manages host-to-host communications, segmentation, flow control, and reliability (TCP).',
   'Layer 3 handles IP routing across networks; Layer 4 handles process-to-process transport and reliability.',
   datetime('now')),

  ('seed-databases-1', 'databases', 'Databases & SQL Theory', 'ACID', 'mcq', 'intermediate',
   'In relational database ACID properties, what does ''Isolation'' guarantee?',
   NULL,
   NULL,
   '["Transactions survive system crashes permanently", "Concurrent transactions execute without interfering with one another", "All foreign key constraints remain valid", "Either all operations in a transaction complete or none do"]',
   1,
   'Isolation ensures that intermediate states of concurrent transactions are invisible to one another, preventing dirty reads and race conditions.',
   'Isolation levels (Read Committed, Repeatable Read, Serializable) balance concurrency with anomaly prevention.',
   datetime('now')),

  ('seed-oop-1', 'oop', 'OOP & System Design Patterns', 'SOLID', 'mcq', 'intermediate',
   'In SOLID principles, what does the ''L'' (Liskov Substitution Principle) state?',
   NULL,
   NULL,
   '["A class should only have one reason to change", "Subtypes must be substitutable for their base types without altering program correctness", "Software entities should be open for extension but closed for modification", "High-level modules should not depend on low-level modules"]',
   1,
   'LSP guarantees that subclasses honor the contracts and preconditions/postconditions of their base classes without unexpected side effects.',
   'Subclasses must maintain the behavioral invariants established by their parent classes.',
   datetime('now'));
